name: Build Bubble Shooter

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build-game:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - name: 📥 Code Checkout
      uses: actions/checkout@v4

    - name: ⚙️ Cmake run
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DUSE_LOCAL_SDL=OFF

    - name: 🔨 Release build
      run: cmake --build build --config Release

    # ==========================================
    # Upload to Windows
    # ==========================================
    - name: 📦 (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: BubbleShooter-Windows
        path: |
          build/Release/bubbleShooter.exe
          build/Release/*.dll
          build/Release/resources/

    # ==========================================
    # Upload to Mak
    # ==========================================
    - name: 📦 (Mac)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: BubbleShooter-Mac
        path: |
          build/bubbleShooter
          build/resources/
          build/**/*.dylib